# Generated by Django 5.0.7 on 2024-07-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('student', models.CharField(default='None', max_length=10)),
                ('music_url', models.CharField(default='None', max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='calander',
        ),
    ]
