# Generated by Django 4.2.16 on 2024-10-13 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_calendar_value_labor_calendar_value'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='labor_calendar_value',
            new_name='wakeup_calendar_value',
        ),
    ]
