# Generated by Django 5.0.7 on 2024-07-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_calendar_delete_calander'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='calendar',
            new_name='calendar_value',
        ),
    ]
