# Generated by Django 4.2.16 on 2024-10-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_labor_calendar_value_wakeup_calendar_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='labor_calendar_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('student', models.CharField(default='None', max_length=10)),
                ('music_url', models.CharField(default='None', max_length=150)),
            ],
        ),
    ]
