# Generated by Django 4.2.16 on 2024-10-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_labor_calendar_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentInfo',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('birthday', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
